### PR TITLE
adjust sponsor logo size to flexbox

### PR DESCRIPTION
**Pull request by alvinkam33**

### CODE REVIEW

**Review by michelleykim — APPROVED** [review]
tysm for getting this done so quickly! 

i found the content doesns't wrap if we have a lot of sponsors, but i don't think its necessary for HC lol @meleongg thoughts?

image

**Comment by alvinkam33** [comment]
no worries i just forgot to add flex-wrap, should be g now

**Comment by meleongg** [comment]
I added a gold sponsor and am still getting the "no-wrapping" visual bug

image

**Comment by alvinkam33** [comment]
i made it so that it will wrap every 2 logos but if we want it to wrap for each one i can do that

**Comment by meleongg** [comment]
I think it'd be nice to have some spacing in between the logos

**Comment by alvinkam33** [comment]
Added spacing and reduced size a bit just to be safe

**Review by michelleykim — APPROVED** [review]
LGTMMMMMM

**Pull request merged**
