### PR TITLE
Update cmd-f to 2024

### PR DESCRIPTION
**Pull request by lsha0730**
Resolves Issue #336

### CODE REVIEW

**Review by michelleykim — APPROVED** [review]
the changes lgtm!

@meleongg ok so the app doesn't build on Node v18 hence the CI fail. should we fix this

**Comment by meleongg** [comment]
Content changes lgtm but can you create a new branch called cmd-f2024_dev that's a copy of cmd-f2024_main and create a PR to merge ll/cmdf-update-to-2024 into cmd-f2024_dev? This PR currently merges into cmdf2023_dev. 

We'll then create a separate PR merging cmd-f2024_dev -> cmd-f2024_main

**Comment by lsha0730** [comment]
Ignore PR #340,

Just made a whole new corrected PR at #341 

This PR and branch can now be deleted safely

**Comment by lsha0730** [comment]
Ignore PR #340 ,

Just made a whole new corrected PR at #341 

This PR and branch can now be deleted safely

**Pull request closed without merging**
