### PR TITLE
Info section

### LINKED ISSUE #192: Section > Info
- Add background and mobile breakpoints for the first section: "Connect, collaborate, create." and "What's a hackathon?"
- Add all the relevant copy to the site

### PR DESCRIPTION
**Pull request by andykwan1124**
## Description
Closes #192 
This PR includes the Info section for the nwHacks website

Desktop view:
image

Mobile view:
image
image

### CODE REVIEW

**Comment by vincentchiang1** [comment]
great work, it looks amazing :)) is it just me or is the mobile view a little inconsistent with what's expected on Figma?

**Comment by andykwan1124** [comment]
@vincentchiang1 hmmm how so?

**Comment by andykwan1124** [comment]
Oh I see. Lemme change some of the styling

**Review by kevin-zou — APPROVED** [review]
This is kinda fire 🔥 

Don't know too much about the mobile thing that you guys are talking about, but once that's fixed I think this is good to go!

**Comment by vincentchiang1** [comment]
yea the mobile stuff is tricky but great work! i think resolve the conflicts since derek just merged the landing section and we can approve/merge once it all fits together!

**Review by vincentchiang1 — APPROVED** [review]

**Pull request merged**
