### PR TITLE
Last visual fixes

### LINKED ISSUE #262: Change meta tags
Completion Criteria
 - [ ] Use appropriate favicon
 - [ ] Add description meta tag
 - [ ] Add open graph preview image 

all in top of `pages/index.jsx` here:
image

### PR DESCRIPTION
**Pull request by naijwu**
## Description

-  removed floating green elipse
- fixed favicon
- removed halo on right ountain
- removed blur layer from globe to hopefully fix blur on iphone
- hid keychain for mobile site
- removed blur on left mountain (fuzzy on iphone)
- changed header gradients
- added 2022 to navbar
- added links to "Become a Mentor", "Code of Conduct", "Apply Now"
- edited favicon, added og preview image, added description - closes #262 
- added background colour to footer

### CODE REVIEW

**Comment by kozr** [comment]
For me this displays in Safari
image

**Comment by naijwu** [comment]
@kozr does the most recent commit fix the safari render issue? if it does--would you be able to add the blur on this branch again or lmk how you did it?

**Comment by kozr** [comment]
Safari, I think it's better in most cases. The map is back as well.


image
image
image

I'll add the shadow

**Review by DonaldKLee — APPROVED** [review]
lgtm!

**Pull request merged**
