### PR TITLE
fix info events transition cutoff

### PR DESCRIPTION
**Pull request by alvinkam33**

### CODE REVIEW

**Comment by meleongg** [comment]
am I tripping or are there 2 deers on mobile
image

**Comment by michelleykim** [comment]
> am I tripping or are there 2 deers on mobile image

ye it seems like assets/mobile/about/background.png has deer head lol

**Comment by meleongg** [comment]
seeing a weird black line using iPhone 12 Pro, might be a niche bug since I don't see it on iPhone SE 
image

small change: there's an _ in Jennifer's name, could we quickly remove that LOL
image

**Comment by alvinkam33** [comment]
@meleongg removed the underscore quickly lool, as for the black line i'll need to play around with that a bit more, it seems on certain resolutions the backgrounds don't stack right on top of one another

**Comment by meleongg** [comment]
any updates on this one? otherwise I think we can merge on this one for jen's name update

**Comment by alvinkam33** [comment]
i could work on it maybe in the future but ya good to merge this first, the duplicate deer should be removed as well

**Pull request merged**
