### PR TITLE
Mobile optimization

### PR DESCRIPTION
**Pull request by naijwu**
## Description

- Used mobile queries to match mobile site on figma
- Bugfixes 

## Other considerations

- No animations - add later

### CODE REVIEW

**Comment by kozr** [comment]
css between `LAPTOP` and `MOBILE` are still messed up

**Comment by naijwu** [comment]
ripp

**Comment by kozr** [comment]
image
This background shifted down too much.

**Comment by kozr** [comment]
but you're nuts for pumping out so much css in one day hahahahahah

**Comment by naijwu** [comment]
I'm starting to think in px and rem s

**Pull request merged**
